<div class="footer-style">
    <div class="white-div">
        <img class="logo-footer up3d" src="./assets/logonoir.png" alt="logo-footer">
    </div>
    <div class="brown-div"></div>
    <div class="grey-div">
        <div class="footer-position mt-5 me-5 d-flex justify-content-evenly">
            <div class="footer-element">
                <h6>COORDONNEES</h6>
                <br>
                <p>Téléphone: <a href="tel:0478886652">04 72 88 66 52</a></p>

                <p>Email: <a href="mailto:nrcompagny@gmail.com">nrcompagny@gmail.com</a></p>

                <p>LYON, Rhône-Alpes</p>
                <a href="#"><i class="fa-brands fa-facebook fa-2xl" style="color: #64371c;"></i></a> <!--  A modifier plus tard !!  -->
                <a href="#"><i class="fa-brands fa-linkedin fa-2xl" style="color: #64371c;"></i></a> <!--  A modifier plus tard !!  -->
            </div>
            <div class="footer-element-1">
                <h6>FORMATIONS</h6>
                <br>
                <a href="formation.php">Formation Incendie</a><br>
                <a href="formation.php">Formation SST</a><br>
                <a href="formation.php">Formation Defibrilateur</a><br>
                <a href="formation.php">Formation Geste et posture</a><br>
                <a href="formation.php">Formation MAC SST</a><br>
            </div>
            <div class="footer-element-2">
                <h6>INFORMATIONS</h6>
                <br>
                <a href="formation.php">Qui sommes nous ?</a><br>
                <a href="terms.php">Mentions légales</a><br>
                <a href="contact.php">Contactez-nous</a><br>
<!--                <a href="#">Cookies</a><br>-->
<!--                <a href="#">Politique de Confidentialité</a><br>-->
            </div>
        </div>
    </div>
</div>