<div class="footer-style">
    <div class="white-div">
        <img class="logo-footer" src="./assets/logonoir.png" alt="logo-footer">
    </div>
    <div class="brown-div"></div>
    <div class="grey-div">
        <div class="footer-position mt-5 me-5 d-flex justify-content-evenly">
            <div class="footer-element">
                <h6>COORDONNEES</h6>
                <br>
                <p>Téléphone: <a href="tel:0478886652">04 72 88 66 52</a></p>

                <p>Email: <a href="mailto:nrcompagny@gmail.com">nrcompagny@gmail.com</a></p>

                <p>LYON, Rhône-Alpes</p>
                <i class="fa-brands fa-facebook fa-2xl" style="color: #64371c;"></i> <!--  A modifier plus tard !!  -->
                <i class="fa-brands fa-linkedin fa-2xl" style="color: #64371c;"></i> <!--  A modifier plus tard !!  -->
            </div>
            <div class="footer-element-1">
                <h6>FORMATIONS</h6>
                <br>
                <p>Formation Incendie</p>
                <p>Formation SST</p>
                <p>Formation Defibrilateur</p>
                <p>Formation Geste et posture</p>
                <p>Formation MAC SST</p>
            </div>
            <div class="footer-element-2">
                <h6>INFORMATIONS</h6>
                <br>
                <a href="#">Qui sommes nous ?</a><br>
                <a href="#">Mentions légales</a><br>
                <a href="#">Cookies</a><br>
                <a href="#">Politique de Confidentialité</a><br>
            </div>
        </div>
    </div>
</div>