
<div class="footer-style">
<div class="white-div"></div>
<div class="brown-div"></div>
<div class="grey-div">
    <div class="footer-position mt-5 me-5 d-flex justify-content-evenly">
    <div class="footer-element">
    <h6>COORDONNEES</h6>
    <br>
    <p>Téléphone: 04 72 88 66 52</p>
    
    <p>Email: nrcompagny@gmail.com</p>
    
    <p>LYON, Rhône-Alpes</p>
    </div>
    <div class="footer-element-1">
    <h6>FORMATIONS</h6>
    <br>
    <p>Formation Incendie</p>
    <p>Formation SST</p>
    <p>Formation Defibrilateur</p>
    <p>Formation Geste et posture</p>
    <p>Formation MAC SST</p>
    </div>
    <div class="footer-element-2">
    <h6>INFORMATIONS</h6>
    <br>
    <p>Qui sommes nous ?</p>
    <p>Mentions légales</p>
    <p>Cookies</p>
    <p>Politique de Confidentialité</p>
    </div>
    </div>
</div>
</div>


