
<?php if ($page == 1) {  ?>


    <div id="displayback">
        <div>
        <h1 class="">FORMATION PREVENTION ET SECURITE</h1>
        <p>"Développe l'habitude Secouriste"</p>
        </div>
</div>

<?php } ?>
<section>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse justify-content-evenly" id="navbarNav">
      <ul class="navbar-nav ">
        <li class="nav-item">
          <a class="nav-link <?php if ($page == 1) {  echo "active"; }?>" aria-current="page" href="#"> Accueil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">Formations</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
              <img src="http://tyrolium.fr/Contenu/Image/Gamenium%20Site.png" alt="Logo">
            </a>
            
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Calendrier</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</section>