<?php if ($page == 1) {  ?>


  <div id="displayback">
    <div>
      <h1 class="">FORMATION PREVENTION ET SECURITE</h1>
      <p>"Développe l'habitude Secouriste"</p>
    </div>
  </div>

<?php } else { ?>

  <style>
    header li img {
      margin-top: unset !important;
    }

    header li {
      margin-top: auto !important;
    }
  </style>


<?php } ?>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <!-- Bouton de bascule pour le menu burger -->
    <button class="navbar-toggler noBorder" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <!-- Logo centré avec les classes Bootstrap -->
    <a class="navbar-brand mx-auto logo-burger-yes" href="./index.php">
      <img class="logo-header" src="./assets/efze-removebg-preview.png" alt="Logo">
    </a>
    <!-- Contenu de la barre de navigation -->
    <div class="collapse navbar-collapse justify-content-evenly" id="navbarNav">
      <ul class="navbar-nav ">
        <li class="nav-item">
          <a class="nav-link <?php if ($page == 1) {
                                echo "active";
                              } ?>" aria-current="page" href="./index.php"> Accueil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php if ($page == 3) {
                                echo "active";
                              } ?>" href="./formation.php">Formations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link logo-burger-no" href=".">
            <img class="logo-header" src="./assets/efze-removebg-preview.png" alt="Logo">
          </a>

        </li>
        <li class="nav-item">
          <a class="nav-link <?php if ($page == 2) {
                                echo "active";
                              } ?>" href="./calendrier.php">Calendrier</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php if ($page == 4) {
                                echo "active";
                              } ?>" href="./contact.php">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>